### PR TITLE
feat: UI overhaul

### PR DESCRIPTION
**Pull request by sminez**
This PR involves pulling all of the UI related logic out of the main `Editor` and `Buffer` structs so that it is handled centrally in a way that is easier to reason about. It also introduces the concept of a `Window` to draw a distinction between the contents of a given `Buffer` and the user interface _view_ of that `Buffer`.

Management of these windows is going to follow the UI paradigm of acme where the user can decide a number of columns and then move windows between those columns. Unlike acme it is not required that all open buffers have their own window, which means that there is some work to be done around how the user manages and decides when they want to open a _new_ window vs replace the contents of an existing one.

### Demo

https://github.com/user-attachments/assets/11c68637-4a5d-442b-ba8b-d5d2d57077c7

### Future work
- Improvements to automatic window placement
- Caching of rendered content to improve rendering times (not too bad currently but could definitely be better)
- Use of hints from the Editor to determine what needs to be re-rendered
- Better visual indication of the active buffer
- Acme style window tags (see #26 for details)

### CODE REVIEW

**Comment by sminez** [comment]
There is still going to be work to do to improve the UI behaviour and there are likely going to be changes made to both the key bindings and the semantics of the UI operations so I'm not going to call things "stable" at this point but they are working well enough that I'm going to merge this and play around with it for a while before publishing a new release.

**Comment by srenatus** [comment]
Wohoo. This is really nice. I've got the diff view open to remember the new keybindings, but it is really nice to have more than one window in an ad session ❤️ thanks!

**Comment by sminez** [comment]
Thanks @srenatus! I want / need to get some auto-generated docs for the key bindings into `:help` in the same way as the built in commands so that things are easier to check. I have a few ideas about how to handle that but it'll take a bit of work to sort it out so it'll take some time before I can land it I'm afraid.

**Comment by srenatus** [comment]
It's fine, no need to rush this from my end 👍 Thanks!

**Pull request merged**
